import type { CustomerType, DishType } from '../types/game';

export const customerTypes: CustomerType[] = [
  {
    type: 'pig',
    name: 'Pig Girl',
    preferredDishes: ['blue', 'red'],
    baseDeliciousness: 2,
    description: 'Loves hearty main courses and sweet desserts',
  },
  {
    type: 'cow',
    name: 'Cow Girl',
    preferredDishes: ['green', 'yellow'],
    baseDeliciousness: 3,
    description: 'Enjoys soups and substantial meals',
  },
  {
    type: 'sheep',
    name: 'Sheep Girl',
    preferredDishes: ['blue', 'green'],
    baseDeliciousness: 2,
    description: 'Prefers light appetizers and warm soups',
  },
  {
    type: 'rabbit',
    name: 'Rabbit Girl',
    preferredDishes: ['blue', 'red'],
    baseDeliciousness: 1,
    description: 'Loves appetizers and desserts',
  },
  {
    type: 'cat',
    name: 'Cat Girl',
    preferredDishes: ['yellow', 'blue'],
    baseDeliciousness: 4,
    description: 'Enjoys main courses and appetizers',
  },
  {
    type: 'deer',
    name: 'Deer Girl',
    preferredDishes: ['green', 'blue'],
    baseDeliciousness: 3,
    description: 'Polite and shy, prefers fresh greens and forest-inspired dishes',
    specialTraits: { lowAppetite: true },
  },
  {
    type: 'duck',
    name: 'Duck Girl',
    preferredDishes: ['yellow', 'green'],
    baseDeliciousness: 2,
    description: 'Quirky and loud, loves bread-based meals and waterfowl-friendly soups',
    specialTraits: { canWander: true },
  },
  {
    type: 'chicken',
    name: 'Chicken Girl',
    preferredDishes: ['yellow', 'red'],
    baseDeliciousness: 2,
    description: 'Nervous and fussy, prefers grain-based meals and fried snacks',
    specialTraits: { multipliesOnProcess: true },
  },
  {
    type: 'fish',
    name: 'Fish Girl',
    preferredDishes: ['blue', 'green'],
    baseDeliciousness: 4,
    description: 'Laid-back and cool, enjoys seaweed, sushi, and lighter fare',
    specialTraits: { fastSpoilage: true },
  },
  {
    type: 'fox',
    name: 'Fox Girl',
    preferredDishes: ['red', 'yellow'],
    baseDeliciousness: 3,
    description: 'Cunning and playful, loves spicy dishes and street food',
    specialTraits: { canStealFood: true },
  },
  {
    type: 'goat',
    name: 'Goat Girl',
    preferredDishes: ['green', 'yellow'],
    baseDeliciousness: 2,
    description: 'Stubborn and quirky, enjoys chewy foods and herbs',
    specialTraits: { canEatWaste: true },
  },
  {
    type: 'bear',
    name: 'Bear Girl',
    preferredDishes: ['red', 'yellow'],
    baseDeliciousness: 5,
    description: 'Big appetite and warm demeanor, loves honey desserts and hearty stews',
    specialTraits: { highYield: true },
  },
  {
    type: 'monkey',
    name: 'Monkey Girl',
    preferredDishes: ['red', 'blue'],
    baseDeliciousness: 2,
    description: 'Energetic and cheeky, prefers fruits and finger foods',
    specialTraits: { throwsFood: true },
  },
];

export const dishTypes: DishType[] = [
  {
    color: 'blue',
    name: 'Appetizers',
    cookTime: 3000,
    examples: ['Spring Rolls', 'Cheese Bites', 'Mini Salads'],
  },
  {
    color: 'green',
    name: 'Soups',
    cookTime: 5000,
    examples: ['Vegetable Soup', 'Bone Broth', 'Mushroom Bisque'],
  },
  {
    color: 'yellow',
    name: 'Main Courses',
    cookTime: 7000,
    examples: ['Grilled Steaks', 'Roasted Chicken', 'Pasta Dishes'],
  },
  {
    color: 'red',
    name: 'Desserts',
    cookTime: 4000,
    examples: ['Chocolate Cake', 'Ice Cream', 'Fruit Tarts'],
  },
];
